version: '3.3'
services:
  db:
    #mysql image
    image: mysql:8.0.2
    container_name: mysql.8.0.2
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: test   
      # MYSQL_PASSWORD: test  
      MYSQL_DATABASE: 'mycity'
    ports:
      - '3306:3306'
    volumes:
      - "/Users/siniv/docker/volume/mysql.8.0.2"
      - "/Users/siniv/docker/volume/mysql.8.0.2/conf.d"
