# docker-compose-postgres.yml
version: '3.5'

services:
  postgresdb:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB:  emm
      #PGDATA: /data/postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
       - postgres:/var/lib/postgresql/data
       #- ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create tables
       - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
       - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        # copy the sql script to fill tables
       - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-venkat.jee1004@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres-network
    restart: unless-stopped

networks:
  postgres-network:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    